Do not call reset in onAbandoned() callback. At that point the object was not remembered so nothing important (like coroutineScope) was initialized thus there is nothing to reset.
Fixes crash "Unhandled exception in thread: main, error:
kotlin.UninitializedPropertyAccessException: lateinit property coroutineScope
has not been initialized".